default: production
environments:
  local: ""
  staging: ""
  production: "https://dp-dev.q1-team.com/login"
users:
  admin:
    username: "test_admin@quantumone.ae"
    password: "Z(200907515792uv"
  user:
    username: "test_user@quantumone.ae"
    password: "NewPass1234!"
    new_pass: "NewPass123!"
    password_outlook: "T!650876172432up"
